services:
  web:
    container_name: porto
    image: dickyjoelsaputra/porto:latest
    expose:
      - "8080"
    volumes:
      - ./index.html:/app/index.html
      - ./css:/app/css
      - ./js:/app/js
      - ./images:/app/images
    networks:
      - shared_network
    restart: unless-stopped

networks:
  shared_network:
    external: true
