services:
  web:
    container_name: porto
    image: dickyjoelsaputra/porto:latest
    expose:
      - "8080"
    networks:
      - npm
    restart: unless-stopped

networks:
  npm:
    external: true