# Generated by Django 5.1.7 on 2025-07-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioAdmin",
            fields=[],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("personal.portfolio",),
        ),
    ]
