# Generated by Django 5.1.7 on 2025-07-05 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_portfolioadmin"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PortfolioAdmin",
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
